### ISSUE TITLE
Where can I see the API documentation?

### ISSUE THREAD

**Issue by ricodex** [rizalihwan/screencast-api#1]
Hi Rizal, Where can I see the API documentation? can you please inform me, thanks

**Comment by rizalihwan** [comment]
You can look at https://documenter.getpostman.com/view/13385250/UVsMtjiD or you can directly look at the project in this repository.

**Comment by rizalihwan** [comment]
For future and most updated documentation links, you can see about this repository project, if there is any maintenance or API update you can immediately find out.
